services:
  - type: web
    name: voyagehub
    env: node
    plan: free
    buildCommand: npm install && npm install --prefix server && cd client && npm install && npm run build && cd .. && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: COOKIE_SECRET
        sync: false
      - key: GOOGLE_GEMINI_API_KEY
        sync: false
